[workspace]
members = [
  "pie",
  "graph",
  "dev_util",
  "dev_ext",
]
default-members = [
  "pie",
  "graph",
  "dev_util",
  "dev_ext",
]
resolver = "2"

[patch.crates-io]
serde_flexitos = { path = "../serde_flexitos" }
