cargo-features = ["named-profiles", "profile-overrides"]

[workspace]
members = [
  "pie",
  "graph",
  "dev_util",
  "dev_ext",
]
default-members = [
  "pie",
  "graph",
  "dev_util",
  "dev_ext",
]
resolver = "2"
