name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, windows-2022, macos-13 ]
    runs-on: ${{ matrix.os }}
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - id: setup-rust
        name: Setup Rust
        uses: moonrepo/setup-rust@v1
      - id: test
        name: Test
        run: cargo test
